name: Django-pipeline

on:
  push:
    branches:
      - shaik
      - cicd-test
    tags:
      - '*'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    needs: []

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          echo "--------------installing the requirements-------------------------"
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # test:
  #   runs-on: ubuntu-latest
  #   if: "!startsWith(github.ref, 'refs/tags/')"
  #   needs: compile

  #   steps:
  #     # Your test steps here...

  # Image-build-and-push:
  #   # Your existing steps...

  # Create-Helm-Chart:
  #   # Your existing steps...

  # dev-deployment:
  #   # Your existing steps...

  # health-check:
  #   # Your existing steps...
