name: Compile Pipeline

on:
  workflow_dispatch:
    inputs:
      compile:
        description: 'Run compile job manually'
        runs-on: ubuntu-latest
        outputs:
          result: ${{ steps.check.outputs.result }}

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          echo "--------------installing the requirements-------------------------"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Record the result
        id: check
        run: echo "::set-output name=result::success"
