name: Two Stage CI/CD

on:
  push:
    branches:
      - shaik

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  code-test:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r .
        continue-on-error: true
        
      - name: Install Safety
        run: |
          pip install safety

      - name: Run Safety
        run: |
          safety check --full-report

  Image-build-and-push:
    runs-on: ubuntu-latest
    needs: code-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        
        env:
          runs-on: ubuntu-latest
          DOCKER_USERNAME: shaikbyte
          DOCKER_PASSWORD: Cooper@18041996
          TAG: ${{ github.sha }}
        
        run: |
          docker build -t first-image .
          docker image ls
          docker tag first-image shaikbyte/django-ecommer:1
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
          trivy image first-image:1
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
          # docker tag shaik shaikbyte/django-ecommer:${TAG}
          docker push shaikbyte/django-ecommer:1
          


