name: Two Stage CI/CD

on:
  push:
    branches:
      - shaik

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  code-test:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r .
        continue-on-error: true
        
      - name: Install Safety
        run: |
          pip install safety

      - name: Run Safety
        run: |
          safety check --full-report

  Image-build-and-push:
    runs-on: ubuntu-latest
    needs: code-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: shaikbyte
          DOCKER_PASSWORD: Cooper@18041996
          TAG: ${{ github.sha }}
        
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t . .
      - name: Login to Docker Hub
        run: |
         echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - name: Tag Docker image
        run: |
         docker tag django-ecommer-api shaikbyte/django-ecommer:${TAG}
      - name: Push Docker image
        run: |
         docker push shaikbyte/django-ecommer:${TAG}


